services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ONNX_MODEL_NAME: ${ONNX_MODEL_NAME}
        ONNX_MODEL_URL: ${ONNX_MODEL_URL}
        LABELS_MAP_PATH: ${LABELS_MAP_PATH}
        LABELS_MAP_URL: ${LABELS_MAP_URL}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./upload_files:/app/upload_files
    depends_on:
      - db
  db:
    container_name: db
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
volumes:
  mongo_data:
  upload_files:
